name: components_codelab
description: An AngularDart app that simulates a lottery
version: 0.0.1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  intl: ^0.15.0

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.5.0
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
  test: ^1.6.0

